### ISSUE TITLE
issue with triying to test this out.

### ISSUE THREAD

**Issue by hirokku** [umihico/laravel-lambda-docker-bref#3]
Hello @umihico 

I am trying to test this, but when I run:

curl -s https://laravel.build/larademo | bash

I get: Docker is not running.

I am pretty sure docker is running since when I run:

sudo systemctl status docker

I get:

 docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset>
     Active: active (running) since Sat 2021-04-03 23:49:48 UTC; 13min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 3806 (dockerd)
      Tasks: 11
     Memory: 98.1M
     CGroup: /system.slice/docker.service
             └─3806 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/cont>

Apr 03 23:49:47 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:47.90867>
Apr 03 23:49:47 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:47.90901>
Apr 03 23:49:48 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:48.08018>
Apr 03 23:49:48 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:48.16133>
Apr 03 23:49:48 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:48.25428>
Apr 03 23:49:48 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:48.25469>
Apr 03 23:49:48 ip-172-31-39-201 systemd[1]: Started Docker Application Contain>
Apr 03 23:49:48 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:49:48.30820>
Apr 03 23:57:11 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:57:11.66323>
Apr 03 23:58:50 ip-172-31-39-201 dockerd[3806]: time="2021-04-03T23:58:50.88340>

Thanks in advance.

**Comment by umihico** [comment]
@hirokku 
Hello, Thank you for checking out my repository.

Could you check again that your docker is running by this command? 

```bash
docker run hello-world
```
